name: "Setup Java"
description: "Adds Java and Maven"
runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: temurin
        server-id: set-github
        cache: maven

    - name: Setup Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.3

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        # re-cache on changes in the pom and target files
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
          ${{ runner.os }}-maven-

    - name: Copy repository local maven settings
      shell: bash
      run: cp $GITHUB_ACTION_PATH/settings.xml ~/.m2/settings.xml