# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.
name: License vetting status check
on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}
  pull_request:
    branches:
      - ${{ github.event.repository.default_branch }}
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license-check:
    # don't run this workflow in forks and only for changes to the default branch
    if: github.repository == 'netomi/macos-notarization-service' && 
        github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    uses: eclipse/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      projectId: technology.cbi
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}
