name: License Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  issue_comment:
    types: [created]
  workflow_dispatch:

env:
  projectId: "technology.cbi"

permissions:
  contents: read
  pull-requests: write

jobs:
  ort:
    runs-on: ubuntu-22.04
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          run: 'cache-dependencies,analyzer,upload-results'
          image: 'ghcr.io/netomi/ort-minimal:1.0.0-14460.sha.8d413c3'
          log-level: 'info'
          sw-name: 'artifact'
          sw-version: 'latest'

  check-licenses:
    if: github.event_name != 'issue_comment' || (github.event.issue.pull_request && (contains(github.event.comment.body, '/request-license-review') || contains(github.event.comment.body, '/license-check')))

    # Run on all non-comment events specified by the calling workflow and for comments on PRs that have a corresponding body.
    runs-on: ubuntu-22.04
    needs: ['ort']
    steps:
      - name: Check dependabot PR
        run: echo "isDependabotPR=1" >> $GITHUB_ENV
        if: >
          github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
          && github.actor == 'dependabot[bot]' && github.actor_id == '49699333'
        # For 'issue_comment'-events this job only runs if a comment was added to a PR with body specified above

      - name: Check PR
        run: echo "isPR=1" >> $GITHUB_ENV
        if: >
          github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')

      - name: Set review request
        run: echo "request-review=1" >> $GITHUB_ENV
        if: (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/request-license-review'))

      - name: Set license check
        run: echo "license-check=1" >> $GITHUB_ENV
        if: (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/license-check')) || env.isDependabotPR

      - name: Process license-vetting request
        if: (env.request-review || env.license-check) && (!env.isDependabotPR)
        uses: actions/github-script@v6
        with:
          script: |
            const payload = await github.rest.repos.getCollaboratorPermissionLevel({
              ...context.repo, username: context.actor
            });
            const userPermission = payload?.data?.permission;
            let reaction = 'rocket'
            if (!(userPermission == 'write' || userPermission == 'admin')) { // not a committer
              // Not a committer -> abort workflow
              core.setFailed("Only committers are permitted to request license vetting and " + context.actor + " isn't one.")
              reaction = '-1'
            }
            // react on comment to give early feedback that the request was understood
            await github.rest.reactions.createForIssueComment({
              ...context.repo, comment_id: context.payload?.comment?.id, content: reaction
            });

      # By default the git-ref checked out for events triggered by comments to PRs is 'refs/heads/master'
      # and for events triggered by PR creation/updates the ref is 'refs/pull/<PR-number>/merge'.
      # So by default only the master-branch would be considered when requesting license-reviews, but we want the PR's state.
      # Unless the PR is closed, then we want the master-branch, which allows subsequent license review requests.
      - uses: actions/checkout@v4
        # use default ref 'refs/pull/<PR-number>/merge' for PR-events and 'refs/heads/master' for comments if the PR is closed
        if: github.event.issue.pull_request == '' || github.event.issue.state != 'open'
        with:
          submodules: ${{ inputs.submodules }}
      - uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/merge"
          submodules: ${{ inputs.submodules }}
        if: github.event.issue.pull_request != '' && github.event.issue.state == 'open'

      - uses: actions/download-artifact@v3
        with:
          name: ort-results-artifact-latest

      - name: Check license vetting status (and ask for review if requested)
        id: check-license-vetting
        uses: netomi/macos-notarization-service/.github/actions/check-dependencies@main
        with:
          request-review: ${{ env.request-review }}
          project-id: ${{ env.projectId }}
        env:
          GITLAB_API_TOKEN: ${{ secrets.gitlabAPIToken }}

      # Hide outdated License comments
      - uses: int128/hide-comment-action@a3bd9d480e857c8047d7d869e8fc87c43ae039f8 # v1.28.0
        if: (env.request-review || env.license-check || env.isPR) && (!env.isDependabotPR)
        with:
          ends-with: |
            <!-- tag-license-comment -->

      - name: Process license check results
        if: (env.request-review || env.license-check || env.isPR) && (!env.isDependabotPR)
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const reviewRequested = ${{ env.request-review || false }}
            const updateRequested = reviewRequested || ${{ env.license-check || false }}
            const licensesVetted = ${{ steps.check-license-vetting.outputs.licenses-vetted }}

            let commentBody = "### License summary\n"
            if (licensesVetted)
            {
              if(updateRequested)
              {
                commentBody += ':heavy_check_mark: All licenses already successfully vetted.\n'
              }
              else 
              {
                // Do not comment if all licenses are vetted and no update was requested 
                core.info('All licenses are already vetted.')
                return;
              }
            }
            else 
            {
              // Print dependency info 
              const dependencySummaryFile = 'DEPENDENCIES'
              core.info("Read dependency summary at " + dependencySummaryFile)
              let content = "";
              if (fs.existsSync(dependencySummaryFile)) {
                content = fs.readFileSync(dependencySummaryFile, { encoding: 'utf8' }).trim();
              }

              if (content) { // not empty
                commentBody += ":x: Not yet vetted dependencies:\n"
                commentBody += "| Dependency | License | Status | Ticket |\n"
                commentBody += "|------------|---------|--------|--------|\n"
                const lines = content.split('\n')
                for (const line of lines) {
                  if(line.includes('restricted')) {
                    const values = line.split(", ")
                    let ticket = values[3]
                    if (ticket.includes("#")) {
                       ticket = `[${ticket}](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/${ticket.substring(1)})`
                    }
                    commentBody += `| ${values[0]} | ${values[1]} | ${values[2]} | ${ticket} |\n`
                  }
                }
              } else {
                commentBody += ':warning: Failed to process DEPENDENCIES.\n'
              }

              if(reviewRequested)
              {
                const reviewSummaryFile = "target/dash/review-summary"
                let reviews = "";
                if (fs.existsSync(reviewSummaryFile)) {
                  reviews = fs.readFileSync(reviewSummaryFile, { encoding: 'utf8' }).trim();
                }
                if (reviews) { // not empty
                  commentBody += "\n### :rocket: Requested reviews:\n"
                  const lines = reviews.split('\n')
                  for (const line of lines) {
                    commentBody += `- ${line}\n`
                  }
                } else {
                  core.setFailed("License vetting build failed, but no reviews are created")
                  commentBody += ':warning: Failed to request review of not vetted licenses.\n'
                }
              }

              commentBody += '\n\n- Committers can request a license review via by commenting `/request-license-review`.\n- After all reviews have concluded, Committers can re-run the license-vetting check by commenting `/license-check`\n'

            }

            commentBody += `\nWorkflow run (with attached summary files):\n${context.serverUrl}/${process.env.GITHUB_REPOSITORY}/actions/runs/${context.runId}`
            commentBody += '\n<!-- tag-license-comment -->'
            github.rest.issues.createComment({
              issue_number: context.issue.number, ...context.repo, body: commentBody
            })

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: "${{ inputs.projectId }}-license-vetting-summary"
          path: |
            DEPENDENCIES
            target/dash/review-summary