name: License Check

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          run: 'cache-dependencies,analyzer,upload-results'
          image: 'ghcr.io/netomi/ort-minimal:1.0.0-14457.sha.a53c6ec'
          log-level: 'info'
